name: Linux build

on:
  push:
    paths:
     - binary/**
  pull_request:

jobs:
  build-linux-so-binary:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install required build packages
      run: |
       sudo apt-get update
       sudo apt-get update --fix-missing
       sudo apt-get install dos2unix
       sudo apt install build-essential
       sudo apt install gcc
       sudo apt install clang
       sudo apt install libc6-dev-i386
       sudo apt-get install gcc-multilib g++-multilib
    - name: Build aura.so
      working-directory: binary/linux
      run: |
       chmod +x gendbg.sh
       dos2unix gendbg.sh
       make aura
    - name: Publish Linux server binary.
      uses: actions/upload-artifact@v4
      with:
            path: |
                /home/runner/work/Aura-SE/Aura-SE/binary/linux/release/aura.so
                /home/runner/work/Aura-SE/Aura-SE/binary/linux/release/aura.so.dbg
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
