name: Linux build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux-so-binary:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install required build packages
      run: |
       sudo apt-get update
       sudo apt-get update --fix-missing
       sudo apt install build-essential
       sudo apt install gcc
       sudo apt install clang
       sudo apt install libc6-dev-i386
       sudo apt-get install gcc-multilib g++-multilib
    - name: Build aura.so
      working-directory: binary/linux
      run: make
    #- name: make check
      #run: make check
    #- name: make distcheck
      #run: make distcheck
